name: Automated Tests

# Когда запускать? При каждом пуше в любую ветку
on: [push]

jobs:
  test:
    # На какой машине запускать? (Виртуальная машина Linux)
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем твой код из репозитория на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Java 17 (как у тебя локально)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Даем права на выполнение файлу gradlew (специфика Linux)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. ЗАПУСК ТЕСТОВ
      # Обрати внимание на флаг -Dselenide.headless=true
      # Он заставит Selenide работать без монитора
      - name: Run Tests with Gradle
        run: ./gradlew clean test -Dselenide.headless=true

      # 5. (Опционально) Публикация отчетов, если тесты упали
      # Мы настроим это позже, пока главное - чтобы прошло выполнение.